alamy/urls.py
from django.urls import path   
from . import views
app_name = 'alamy'
urlpatterns = [	


 path('listpost', views.listpost,name='listpost'),
    path('recharge', views.recharge,name='recharge'),
    path('univer', views.univer,name='univer'),
    path('communication', views.communication,name='communication'),
    path('get_comments/<int:poste_id>/', views.get_comments, name='get_comments'),
    path('login', views.login_user,name='login'),
    path('service', views.service,name='service'),
    path('iset', views.iset,name='iset'),
    path('index', views.index, name='index'),
    path('accueuil',views.accueuil,name='accueuil'),
     path('jeux',views.jeux,name='jeux'),
    path('',views.poste,name='poste'),
    path('logement',views.logements,name='logement'),
    path('stage',views.stages,name='stage'),
    path('filtre/',views.filtrer,name='filtre'),
    path('resultas/',views.resultas,name='resultas'),
     path('transport', views.transport_liste, name='transport'),
    path('evenement', views.evenement_liste, name='evenement'),
    path('qui-sommes-nous/', views.qui_sommes_nous, name='qui_sommes_nous'),
    path('contacter/', views.contacter, name='contact'),
    path('ajout-utilisateur/', views.ajout_utilisateur, name='ajout_utilisateur'),
    path('like-post/<int:poste_id>/', views.like_post, name='like_post'),
    path('dislike-post/<int:poste_id>/', views.dislike_post, name='dislike_post'),
    path('add-comment/<int:poste_id>/', views.add_comment, name='add_comment'),
    path('poste/<int:poste_id>/', views.detail, name='detail'),
     path('ajouter_reaction/<int:poste_id>/', views.ajouter_reaction, name='ajouter_reaction'),
     path('page_utilisateur/', views.page_utilisateur, name='page_utilisateur'),
      path('modify/<int:poste_id>/', views.modify_post, name='modify_post'),
    path('delete/<int:poste_id>/', views.delete_post, name='delete_post'),
    path('admine', views.admine,name='admine'),
path('ListePartenaire',views.ListePartenaire,name='ListePartenaire'),

path('qui-sommes-nous_admin/', views.qui_sommes_nous_admin, name='qui_sommes_nous_admin'),

path('supprimer_poste/<int:admine_id>/', views.supprimer_poste, name='supprimer_poste'),
    path('supprimer_user/<int:admine_id>/', views.supprimer_user, name='supprimer_user'),
path('filtreadmin/',views.filtreadmin,name='filtreadmin'),
path('resultasadmin/',views.resultasadmin,name='resultasadmin'),
path('ajouter_stage/', views.ajouter_stage, name='ajouter_stage'),
path('ajouter_transport/', views.ajouter_transport, name='ajouter_transport'),
path('ajouter_logement/', views.ajouter_logement, name='ajouter_logement'),
path('ajouter_even_soc/', views.ajouter_even_soc, name='ajouter_even_soc'),
path('ajouter_even_club/', views.ajouter_even_club, name='ajouter_even_club'),
path('reserver_poste/<int:poste_id>/', views.reserver_poste, name='reserver_poste'),
path('voir_reservations_poste/<int:poste_id>/', views.voir_reservations_poste, name='voir_reservations_poste'),
path('modify_reservation/<int:reservation_id>/', views.modify_reservation, name='modify_reservation'),
path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),







   




  ]

myprojet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alamy.urls')),  # Include alamy app URLs


]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

alamy/models.py
from django.db import models


class Utilisateur(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    motdepasse = models.CharField(max_length=100,default='')  

    def __str__(self):
        return f" {self.nom}  {self.prenom} {self.telephone} {self.email} "

class Poste(models.Model):
    TYPE_CHOICES = [
        (0, 'Offre'),
        (1, 'Demande'),
    ]

    type = models.IntegerField(choices=TYPE_CHOICES)
    image = models.ImageField(null=True, blank=True)
    utilisateur = models.ForeignKey('Utilisateur', on_delete=models.CASCADE, null=True)
    likes_count = models.IntegerField(default=0)
    dislikes_count = models.IntegerField(default=0)
    comments_count = models.IntegerField(default=0)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.type} {self.image} {self.utilisateur}"

class Evenement(Poste):
    intitule = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    
    date = models.DateField()
    lieu = models.CharField(max_length=100)
    contactinfo = models.CharField(max_length=100)
    nombretickets = models.IntegerField(blank=True, null=True)
    def save(self, *args, **kwargs):
            if self.nombretickets == 0:
              self.is_deleted = True
            super(Evenement, self).save(*args, **kwargs)


    def __str__(self):
        return f"{self.intitule} {self.description} {self.date} {self.lieu} {self.contactinfo} { self.nombretickets}"



class Reaction(models.Model):
    
    like = models.BooleanField(default=False, null=True)  
    dislike = models.BooleanField(default=False, null=True)
    
    comment = models.TextField(default=False, null=True)
    poste = models.ForeignKey(Poste, on_delete=models.CASCADE)



    def __str__(self):
     return f"  {self.like} {self.dislike} {self.comment} {self.poste} "


class Stage(Poste):
    TYPE_CHOICES = [
        (1, 'Ouvrier'),
        (2, 'Technicien'),
        (3, 'PFE'),
    ]
    typeStg = models.IntegerField(choices=TYPE_CHOICES)
    societe = models.CharField(max_length=100)
    duree = models.IntegerField()
    sujet = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    lieu = models.CharField(max_length=100, default='')


    def __str__(self):
     return f"{self.typeStg} {self.societe} {self.duree} {self.sujet} {self.description} {self.lieu} "

class Logement(Poste):
    localisation = models.CharField(max_length=100)
    description = models.CharField(max_length=100,null='true')

    contactinfo = models.CharField(max_length=100)
    nombreTables = models.IntegerField(blank=True, null=True)
    def save(self, *args, **kwargs):
            if self.nombreTables== 0:
              self.is_deleted = True
            super(Logement, self).save(*args, **kwargs)

    
    def __str__(self):
     return f" {self.localisation} {self.contactinfo} {self.description} {self. nombreTables} "


class Transport(Poste):
    depart = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    heuredep = models.TimeField()
    contactinfo = models.CharField(max_length=100)
    nombreplaces = models.IntegerField(blank=True, null=True)
    def save(self, *args, **kwargs):
            if self.nombreplaces == 0:
              self.is_deleted = True
            super(Transport, self).save(*args, **kwargs)


    def __str__(self):
     return f" {self.depart} {self.destination} {self.heuredep}  {self.contactinfo}{self.nombreplaces} "

class Recommandation(Poste):
    texte = models.CharField(max_length=255)

    def __str__(self):
     return f" {self.texte} "

class EvenementClub(Evenement):
    club = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.club}"

class EvenementSocial(Evenement):
    prix = models.FloatField()
    specialite = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.prix} {self.specialite}"
class Reservation(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField()
    
    date_rendez_vous = models.DateField(blank=True, null=True)
    nombre_places = models.IntegerField(blank=True, null=True)
    telephone = models.CharField(max_length=20)
    date = models.DateField(blank=True, null=True)
    heure = models.TimeField(blank=True, null=True)
    nombre_Tables4 = models.IntegerField(blank=True, null=True)
    nombre_tickets = models.IntegerField(blank=True, null=True)
    poste = models.ForeignKey(Poste, on_delete=models.CASCADE, related_name='reservation')


    def __str__(self):
        return f"Reservation for {self.poste} by {self.prenom} {self.nom}  {self.email}  {self.telephone}  {self.date}  {self. date_rendez_vous} {self.nombre_Tables4} {self.  nombre_tickets} { self.nombre_places}{self.heure}  "




 

alamy/templates/Evenement.html
{% extends 'accueuil.html' %}

{% block head %}
{% load static %}

    <style>
        
    </style>
{% endblock %}

{% block body %}
    <div class="card-container">
        {% for evenement  in evenements %}
            <div class="card">
                <p class="poste-type">{{ evenement.get_type_display }}</p>
                {% if evenement.image %}
                    <img src="{{ evenement.image.url }}" alt="Image du evenement">

                {% endif %}
                <p class="poste-info">{{ evenement.intitule }}</p> 
                <p class="poste-info">{{ evenement.date }}</p>
                <div class="reactions">
                    <span class="reaction-icon like-icon" data-poste-id="{{ poste.id }}" id="dropdowns-button">&#x1F44D;</span>
                    <span class="likes-count">{{ poste.likes_count }}</span>
                    
                    <span class="reaction-icon dislike-icon" data-post-id="{{ post.id }}" id="dislike-button">&#x1F44E;</span>
                    <span class="dislikes-count">{{ poste.dislikes_count }}</span>
        
                    <span class="reaction-icon comment-icon">&#x1F4AC;</span>
                    <span class="comments-count">{{ poste.comments_count }}</span>
                </div>
                
            </div>
        {% endfor %}
    </div>
    <script>
        document.querySelectorAll('.card').forEach(card => {
            card.addEventListener('click', function() {
                const url = this.getAttribute('data-url');
                window.location.href = url;
            });
        });
    </script>
{% endblock %}

alamy/templates/Partenaire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajout Utilisateur</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
          body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to right, #87559b, #383c60);
            color: black; /* Couleur du texte */
            margin: 0;
            padding: 0;
            
        
        }
        .form-container
{
    margin-top: 50px;
    text-align: center;
      margin-left: 500px;
      width: 500px;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
}
.form-container h1 {
      margin-top: 0;
    }
    .form-container form {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }
    .form-container label {
      display: block;
      margin-bottom: 0.5rem;
      font-weight: bold;
    }
    .form-container input, .form-container select {
      padding: 0.5rem;
      border: 1px solid #ccc;
      border-radius: 4px;
    }
    .form-container button {
      background-color: white;
      color: violet;
      padding: 0.75rem 1rem;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    .form-container button:hover {
      background-color: violet;
    }


.mb-0
{
    margin-left: 200px;
}
       

            

    </style>
</head>
<body>

    <div class="container">
        <div class="row align-items-center">
            <div class="col-auto">
                <a href="{% url 'alamy:poste' %}" class="btn btn-link"><i class="bi bi-chevron-left text-dark"></i></a>
            </div>
            <div class="col">
                <h1 class="mb-0">Devenir Partenaire</h1>
            </div>
        </div>
    </div>
    
    <form method="post" class="form-container">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
</body>
</html>

alamy/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajout Utilisateur</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to right, #87559b, #383c60);
            color: black; 
            margin: 0;
            padding: 0;
            
        }
h1
{
    font-weight: bold;
    text-align: center;
}
#cont
{
    text-align: center;
}
        .container {
            margin-top: 20px;
        }

        h1 {
            font-size: 24px;
            margin-top: 30px;
            margin-bottom: 10px;
            color: black; 
        }

        #ico {
            font-size: 30px;
            margin-left: 700px;
            
        }
        #dd
        {
            font-size: 30px;
            margin-left: 700px;
        }
        #ddd
        {
            font-size: 30px;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="row align-items-center">
            <div class="col-auto">
                <a href="{% url 'alamy:poste' %}" class="btn btn-link"><i class="bi bi-chevron-left text-dark"></i></a>
            </div>
            <div class="col">
                <h2 class="mb-0">Contact</h1>
            </div>
        </div>
    </div>

<div class="cont">
    <h1>C O N T A C T E R - N O U S</h1>

    <a href="https://maps.google.com"><i class="bi bi-geo-alt text-dark" id="ico"></i></a>
<br>
<a href="mailto:info@example.com"><i class="bi bi-envelope text-dark" id="ico"></i></a>
    <br>
    <a href="tel:+123456789"><i class="bi bi-telephone-fill text-dark" id="ico"></i></a>
   


    <h1>S U I V E Z - N O U S </h1>
    <a href="https://www.facebook.com"><i class="bi bi-facebook text-dark" id="dd" ></i></a>
    
    <a href="https://www.instagram.com"><i class="bi bi-instagram text-dark" id="ddd" ></i></a>
  
    <a href="https://www.google.com"><i class="bi bi-globe text-dark" id="ddd"></i></a>

</div>
   
</body>
</html>

alamy/templates/detail.html
{% block head %}
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <style>
       
        
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #333;
        }

       
        .card {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .post-detail {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }

        .post-image {
    margin-right: 10px; 
}
 

img
        {
            width: 500px; 
            
            height: 300px; 
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .post-info {
            flex: 1;
        }

       
        h2 {
            font-size: 24px;
            font-weight: bold;
            color: #8a2be2;
            margin-bottom: 10px;
        }

        p {
            margin-bottom: 10px;
        }

       
        .col-auto .btn {
            color: #333;
            border-color: #ddd;
            background-color: #f8f9fa;
            padding: 10px;
            margin-right: 10px;
            transition: all 0.3s ease;
        }

        .col-auto .btn:hover {
            background-color: #007bff;
            color: #fff;
            border-color: #007bff;
        }

        #comment {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            resize: vertical;
        }

       
        i.fas,
        i.far {
            margin-right: 5px;
        }

       
        .reservation-icon {
            text-align: center;
            margin-bottom: 10px;
        }

        .reservation-icon a {
            font-size: 36px;
            color: #8a2be2;
        }
      
    </style>
{% endblock %}

{% block body %}
<div class="card">
    <div class="col-auto">
        <a href="{% url 'alamy:poste' %}" class="btn btn-link"><i class="bi bi-chevron-left text-dark"></i></a>
    </div>
    {% if poste.stage or poste.transport or poste.logement or poste.evenement %}
    <div class="reservation-icon">
        <a href="{% url 'alamy:reserver_poste' poste.id %}">
            <i class="far fa-calendar-check"></i>
        </a>
    </div>
{% endif %}
    <div class="post-detail">
      
        
        <div class="post-image">
            {% if poste.image %}
                <img src="{{ poste.image.url }}" alt="Image du poste">
            {% endif %}
        </div>

        <div class="post-info">
            {% if poste.stage %}
                <h2>Type: {{ poste.stage.get_typeStg_display }}</h2>
                <p>Société: {{ poste.stage.societe }}</p>
                <p>Durée: {{ poste.stage.duree }}</p>
                <p>Sujet: {{ poste.stage.sujet }}</p>
                <p>Description: {{ poste.stage.description }}</p>
                <p>Lieu: {{ poste.stage.lieu }}</p>
            {% elif poste.evenement %}
                <h2>{{ poste.evenement.intitule }}</h2>
                <p>Description: {{ poste.evenement.description }}</p>
                <p>Date: {{ poste.evenement.date }}</p>
                <p>Lieu: {{ poste.evenement.lieu }}</p>
                <p>Contact: {{ poste.evenement.contactinfo }}</p>
            {% elif poste.logement %}
                <h2>Logement</h2>
                <p>Localisation: {{ poste.logement.localisation }}</p>
                <p>Description: {{ poste.logement.description }}</p>
                <p>Contact: {{ poste.logement.contactinfo }}</p>
            {% elif poste.transport %}
                <h2>Transport</h2>
                <p>Départ: {{ poste.transport.depart }}</p>
                <p>Destination: {{ poste.transport.destination }}</p>
                <p>Heure de départ: {{ poste.transport.heuredep }}</p>
                <p>Contact: {{ poste.transport.contactinfo }}</p>
            {% endif %}
        </div>
    </div>

    <form id="reaction-form" method="post" action="{% url 'alamy:ajouter_reaction' poste.id %}" class="mt-3">
        {% csrf_token %}
        <div class="row align-items-center">
            <div class="col-auto">
                <button type="submit" id="like-btn" onclick="toggleReaction('like')" name="like" class="btn btn-light">
                    <i class="fas fa-thumbs-up"></i> 
                </button>
                <button type="submit" id="dislike-btn" onclick="toggleReaction('dislike')" name="dislike" class="btn btn-light ms-2">
                    <i class="fas fa-thumbs-down"></i> 
                </button>
                <button type="submit" class="btn btn-light ms-2">
                    <i class="fas fa-comment"></i> 
                </button>
                <button type="button" class="btn btn-light ms-2" onclick="openGmailShare()">
                    <i class="fas fa-share"></i> 
                </button>
                
            </div>
        </div>
        
        <div class="mt-3">
            <textarea name="comment" id="comment" class="form-control" rows="3" placeholder="Ajouter un commentaire"></textarea>
        </div>
    </form>
</div>

<script>
    function toggleReaction(reactionType) {
        var reactionBtn = document.getElementById(reactionType + '-btn');
        var isActive = reactionBtn.classList.contains('active');
        if (isActive) {
            reactionBtn.classList.remove('active');
        } else {
            reactionBtn.classList.add('active');
            var otherReactionBtnId = (reactionType === 'like') ? 'dislike-btn' : 'like-btn';
            document.getElementById(otherReactionBtnId).classList.remove('active');
        }
    }

    function openGmailShare() {
        const subject = encodeURIComponent("Partage d'un poste ISET");
        const body = encodeURIComponent(`Je souhaite partager avec vous ce poste:\n\n${document.title}\n\nLien: ${window.location.href}`);
        const mailtoUrl = `https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=&su=${subject}&body=${body}`;
        window.open(mailtoUrl, '_blank');
    }
</script>
{% endblock %}

alamy/templates/recharge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <style>
        body {
            background-color: #f0f0f0;
            color: #333;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin: 20px 0;
            text-align: center;
            color: #333;
        }
        .game-list {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: center;
            padding: 20px;
        }
        .game-card {
            border: 2px solid #ccc;
            border-radius: 10px;
            overflow: hidden;
            width: 200px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
            transition: transform 0.2s;
            background-color: #fff;
        }
        .game-card:hover {
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0,0,0,0.3);
        }
        .game-card img {
            width: 100%;
            height: auto;
        }
        .game-card a {
            display: block;
            padding: 16px;
            text-decoration: none;
            color: #333;
            font-weight: bold;
            background-color: #f0f0f0;
            border-top: 1px solid #ccc;
            transition: background-color 0.2s;
        }
        .game-card a:hover {
            background-color: #e0e0e0;
        }
        .btn-link {
            color: #333;
            text-decoration: none;
        }
        .btn-link:hover {
            color: #666;
        }
    </style>
</head>
<body>
    <a href="{% url 'alamy:poste' %}" class="btn btn-link"><i class="bi bi-chevron-left"></i> </a>
    <h1> Recharge Téléphonique</h1>

    <div class="game-list">
        <div class="game-card">
            <a href="https://www.orange.tn/" target="_blank">
                <img src="../static/css/orange.png" alt="Jeu 4">
                Orange
            </a>
        </div>

        
        <div class="game-card">
            <a href="https://play.google.com/store/apps/details?id=tn.com.tunisiana.android.maTunisiana&hl=fr&gl=US" target="_blank">
                <img src="../static/css/ooredoo.png" alt="Jeu 4">
                Ooredoo
            </a>
        </div>

        
        <div class="game-card">
            <a href="https://play.google.com/store/search?q=tt+telecom&c=apps&hl=fr&gl=US" target="_blank">
                <img src="../static/css/telec.png" alt="Jeu 4">
                Télécome
            </a>
        </div>

     




      

       
    </div>
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

alamy/templates/service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    
    <style>
        body {
            background-color: #f0f0f0;
            color: #333;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin: 20px 0;
            text-align: center;
            color: #333;
        }
        .game-list {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: center;
            padding: 20px;
        }
        .game-card {
            border: 2px solid #ccc;
            border-radius: 10px;
            overflow: hidden;
            width: 200px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
            transition: transform 0.2s;
            background-color: #fff;
        }
        .game-card:hover {
            transform: scale(1.05);
            box-shadow: 0 6px 12px rgba(0,0,0,0.3);
        }
        .game-card img {
            width: 100%;
            height: auto;
        }
        .game-card a {
            display: block;
            padding: 16px;
            text-decoration: none;
            color: #333;
            font-weight: bold;
            background-color: #f0f0f0;
            border-top: 1px solid #ccc;
            transition: background-color 0.2s;
        }
        .game-card a:hover {
            background-color: #e0e0e0;
        }
        .btn-link {
            color: #333;
            text-decoration: none;
        }
        .btn-link:hover {
            color: #666;
        }
    </style>
</head>
<body>
    <a href="{% url 'alamy:poste' %}" class="btn btn-link"><i class="bi bi-chevron-left"></i> </a>
    <h1>Autre Service</h1>

    <div class="game-list">
        <div class="game-card">
            <a href="https://play.google.com/store/apps/details?id=tn.mobipost&hl=fr&gl=US&pli=1" target="_blank">
                <img src="../static/css/d17.png" alt="Jeu 4">
                D17
            </a>
        </div>


        <div class="game-card">
            <a href="{% url 'alamy:iset' %}" target="_blank">
                <img src="../static/css/iset.jpeg" alt="Jeu 4">
                Iset
            </a>
        </div>

        <div class="game-card">
            <a href="{% url 'alamy:communication' %}" target="_blank">
                <img src="../static/css/Rs.png" alt="Jeu 4">
                Application
            </a>
        </div>

        <div class="game-card">
            <a href="https://play.google.com/store/search?q=unicorn&c=movies&hl=fr&gl=US" target="_blank">
                <img src="../static/css/film.png" alt="Jeu 4">
                Film
            </a>
        </div> 
        <div class="game-card">
            <a href="{% url 'alamy:univer' %}" target="_blank">
                <img src="../static/css/serv.png" alt="Jeu 4">
                services universitaires
            </a>
        </div> 
    </div>
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>